name = input('Введите ваше имя: ')
mail = input('Введите ваш адрес: ')
num_tel = input('Введите ваш номер телефона: ')
status = input('Введите специализацию в учебном заведении: ')
print(f'Ваше имя: {name}')
print(f'Ваш адрес: {mail}')
print(f'Ваш номер телефона: {num_tel}')
print(f'Ваш статус: {status}')